### ISSUE TITLE
在Python3.9，3.10上报错，提示“No module named “importlib_metadata”，安装“importlib_metadata”后报错“NotImplementedError”

### ISSUE THREAD

**Issue by expliyh** [MeetWq/nonebot-plugin-logo#5]

**Comment by expliyh** [comment]
06-04 23:23:23 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 41, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 26, in init
    _playwright = await async_playwright().start()
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 199, in run
    await self._transport.connect()
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\playwright\_impl\_transport.py", line 139, in connect
    raise exc
  File "C:\Users\expli\AppData\Local\pypoetry\Cache\virtualenvs\fkqq-nonebot-xZIwrHCf-py3.10\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\expli\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\expli\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\expli\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by MeetWq** [comment]
参考 https://github.com/kexue-z/nonebot-plugin-htmlrender/issues/25

**Comment by expliyh** [comment]
解决了，谢谢啦
